image: node:latest

before_script:
  - npm set registry http://sinopia.linkedsoftwaredependencies.org
  - npm config set @types:registry https://registry.npmjs.org/
  - npm install

cache:
  key: "$CI_PROJECT_PATH/$CI_BUILD_REF_NAME/$NODE_VERSION"
  paths:
  - node_modules/

test_all:
  script:
   - npm test

test_lint:
  script:
   - npm run lint
